// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { zod as z } from "/Users/zhaochuanchuan/Desktop/个人项目/jc-ui/node_modules/@umijs/utils";
import { IConfigFromPluginsJoi } from "./pluginConfigJoi.d";

const IConfig = z.object({});

type IConfigTypes = z.infer<typeof IConfig>;

export type IConfigFromPlugins = IConfigFromPluginsJoi & Partial<IConfigTypes>;
