// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import routeProps from './routeProps.js';

if (process.env.NODE_ENV === 'development') {
  Object.entries(routeProps).forEach(([key, value]) => {
    const internalProps = ['path', 'id', 'parentId', 'isLayout', 'isWrapper', 'layout', 'clientLoader'];
    Object.keys(value).forEach((prop) => {
      if (internalProps.includes(prop)) {
        throw new Error(
          `[UmiJS] route '${key}' should not have '${prop}' prop, please remove this property in 'routeProps'.`
        )
      }
    })
  })
}

import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"docs/test":{"path":"test","id":"docs/test","parentId":"DocLayout"},"components/Button/index":{"id":"components/Button/index","path":"components/button","parentId":"DocLayout"},"components/Card/index":{"id":"components/Card/index","path":"components/card","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout","prerender":false}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/zhaochuanchuan/Desktop/个人项目/jc-ui/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'/Users/zhaochuanchuan/Desktop/个人项目/jc-ui/.dumi/tmp/dumi/theme/ContextWrapper.tsx')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'/Users/zhaochuanchuan/Desktop/个人项目/jc-ui/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'/Users/zhaochuanchuan/Desktop/个人项目/jc-ui/docs/index.md')),
'docs/test': React.lazy(() => import(/* webpackChunkName: "docs__test.md" */'/Users/zhaochuanchuan/Desktop/个人项目/jc-ui/docs/test.md')),
'components/Button/index': React.lazy(() => import(/* webpackChunkName: "Button__index.md" */'/Users/zhaochuanchuan/Desktop/个人项目/jc-ui/src/Button/index.md')),
'components/Card/index': React.lazy(() => import(/* webpackChunkName: "Card__index.md" */'/Users/zhaochuanchuan/Desktop/个人项目/jc-ui/src/Card/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/zhaochuanchuan/Desktop/个人项目/jc-ui/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
