// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/zhaochuanchuan/Desktop/个人项目/jc-ui/node_modules/dumi/theme-default/slots/Features/index.js';
